export type TPurchaseOrderHistory = {
  Id: number;
  Crop: string;
  DocNo: number;
  PoDId: number;
  Amount: number;
  BalQty: number;
  RejQty: number;
  BagPrice: number;
  CityArea: string;
  CommRate: number;
  ItemName: string;
  JobLotId: number;
  Moisture: string;
  PostDate: string;
  PostUser: string;
  BagWeight: number;
  BalWeight: number;
  CompanyId: number;
  EntryUser: number;
  NetWeight: number;
  OrderType: string;
  PPBagRate: string;
  PostState: string;
  TermsCode: string;
  BaseUnitId: number;
  BranchesId: number;
  CommAmount: number;
  Equivalent: number;
  IsApproved: string;
  ItemTypeId: number;
  JobLotCode: string;
  ModifyUser: string;
  ProjectsId: number;
  UOMCodeItm: string;
  ItemClassId: number;
  JuteBagRate: string;
  LabSampleNo: string;
  OrderItemId: number;
  OrderStatus: string;
  PPBagWeight: string;
  ReceivedQty: number;
  UOMCodeRate: string;
  CatagorySrNo: number;
  DeliveryDays: number;
  DeliveryTerm: string;
  ItemCategory: string;
  OrderDueDays: number;
  OrderItemQty: number;
  OrderRemarks: string;
  PurchaseGLAC: number;
  SupplierName: string;
  UserNameAusr: string;
  UserNameEusr: string;
  UserNameMusr: string;
  JuteBagWeight: string;
  OrderItemRate: number;
  OrderTaxable: boolean;
  RemarksHeader: string;
  TaxableStatus: string;
  AmountCalcType: string;
  CommissionType: string;
  DocDate: Date | string;
  DocumentTypeId: number;
  EquivalentRate: number;
  ItemCategoryId: number;
  OrderItemUOMId: number;
  OrderSupCustId: number;
  OrganizationId: number;
  PaymentTermsId: number;
  ReceivedWeight: number;
  CompanyNameSpRp: string;
  DeliveryRemarks: string;
  NoOfAttachments: number;
  OrderCatagoryId: number;
  PurchaseOrderId: number;
  RefrenenceParty: number;
  CompanyNameSpStk: string;
  DocumentTypeCode: string;
  EntryDate: Date | number;
  TermsDescription: string;
  CommissionRemarks: string;
  ItemCode: string | number;
  JobLotDescription: string;
  ModifyDate: Date | string;
  OrderCategoryName: string;
  OrderItemRateUOMId: number;
  CompanyNameSpCAgent: string;
  OrderDueDate: Date | string;
  UomScheduleIdCmRate: number;
  BrokerAgentSupCustId: number;
  OrderExpiryDate: string | Date;
  SupplierRefNo: string | number;
  DocumentTypeDescription: string;
  DeliveryStartDate: Date | string;
  OrderCategoryDescription: string;
  SupplierCustomerIdStockParty: number;
};

export type TPurchaseOrderSearchCriteria = {
  ItemId?: number;
  ToDocNo?: number;
  FromDocNo?: number;
  ToDate?: Date | string;
  FromDate?: Date | string;
  Status?: number | string;
  SupplierCustomerId?: number;
  IsApproved?: number | string;
};

export type TPurchaseOrderMainEntry = {
  Id: number;
  DocNo: number;
  CityId: number;
  CommRate: number;
  PostUser: number;
  CompanyId: number;
  EntryUser: number;
  IsAproved: boolean;
  PostState: boolean;
  CommAmount: number;
  BranchesId: number;
  ModifyUser: number;
  ProjectsId: number;
  BrokeryUom: number;
  BrokeryRate: number;
  OrderStatus: string;
  CatagorySrNo: number;
  DeliveryDays: number;
  OrderDueDays: number;
  DeliveryTerm: string;
  OrderSupCustId: number;
  BrokerAgentId: number;
  BrokeryAmount: number;
  OrderTaxable: boolean;
  CashFreight: boolean;
  AttachmentsList: any;
  DocDate: Date | string;
  DocumentTypeId: number;
  OrganizationId: number;
  PaymentTermsId: number;
  FinancialYearId: number;
  OrderCatagoryId: number;
  RefrenenceParty: number;
  CreditFreight: boolean;
  EntryDate: Date | string;
  ModifyDate: Date | string;
  OrderType: string | null;
  OrderDueDate: Date | string;
  UomScheduleIdCmRate: number;
  BrokeryType: string | null;
  BrokerAgentSupCustId: number;
  CommissionType: string | null;
  RemarksHeader: string | null;
  SupplierRefNo: number | null;
  OrderExpiryDate: Date | string;
  PostDate: Date | string | null;
  DeliveryRemarks: string | null;
  DeliveryStartDate: Date | string;
  CommissionRemarks: string | null;
  PurchaseorderEmptyBagsList: any;
  PurchaseOrderLabDeductionList: any;
  SupplierCustomerIdStockParty: number;
  PurchaseOrderExpensesChargeToProductsList: any;
  purchaseOrderDetailList: TPurchaseOrderDetailEntry[];
};

type TPurchaseOrderDetailEntry = {
  Id: number;
  Amount: number;
  LineId: number;
  UOMCode: string;
  RateUom: string;
  BagPrice: number;
  JobLotId: number;
  ItemName: string;
  BagWeight: number;
  NetWeight: number;
  TaxAmount: number;
  TaxNameId: number;
  RetailRate: number;
  TaxPercent: number;
  TotalAmount: number;
  OrderItemId: number;
  Crop: string | null;
  OrderItemQty: number;
  ActionTypeId: number;
  OrderItemRate: number;
  OrderItemUOMId: number;
  TaxName: string | null;
  UOMDescription: number;
  EquivalentRate: number;
  PurchaseOrderId: number;
  CityArea: string | null;
  Moisture: string | null;
  JobLotDescription: string;
  OrderItemRateUOMId: number;
  LabSampleNo: number | null;
  OrderRemarks: string | null;
  TaxableStatus: string | null;
  AmountCalcType: string | null;
  InvLabSampleAnalysisHeaderId: number;
};
