export type TPurchaseOrderHistory = {
  Id: number;
  Crop: string;
  DocNo: number;
  PoDId: number;
  Amount: number;
  BalQty: number;
  RejQty: number;
  BagPrice: number;
  CityArea: string;
  CommRate: number;
  ItemName: string;
  JobLotId: number;
  Moisture: string;
  PostDate: string;
  PostUser: string;
  BagWeight: number;
  BalWeight: number;
  CompanyId: number;
  EntryUser: number;
  NetWeight: number;
  OrderType: string;
  PPBagRate: string;
  PostState: string;
  TermsCode: string;
  BaseUnitId: number;
  BranchesId: number;
  CommAmount: number;
  Equivalent: number;
  IsApproved: string;
  ItemTypeId: number;
  JobLotCode: string;
  ModifyUser: string;
  ProjectsId: number;
  UOMCodeItm: string;
  ItemClassId: number;
  JuteBagRate: string;
  LabSampleNo: string;
  OrderItemId: number;
  OrderStatus: string;
  PPBagWeight: string;
  ReceivedQty: number;
  UOMCodeRate: string;
  CatagorySrNo: number;
  DeliveryDays: number;
  DeliveryTerm: string;
  ItemCategory: string;
  OrderDueDays: number;
  OrderItemQty: number;
  OrderRemarks: string;
  PurchaseGLAC: number;
  SupplierName: string;
  UserNameAusr: string;
  UserNameEusr: string;
  UserNameMusr: string;
  JuteBagWeight: string;
  OrderItemRate: number;
  OrderTaxable: boolean;
  RemarksHeader: string;
  TaxableStatus: string;
  AmountCalcType: string;
  CommissionType: string;
  DocDate: Date | string;
  DocumentTypeId: number;
  EquivalentRate: number;
  ItemCategoryId: number;
  OrderItemUOMId: number;
  OrderSupCustId: number;
  OrganizationId: number;
  PaymentTermsId: number;
  ReceivedWeight: number;
  CompanyNameSpRp: string;
  DeliveryRemarks: string;
  NoOfAttachments: number;
  OrderCatagoryId: number;
  PurchaseOrderId: number;
  RefrenenceParty: number;
  CompanyNameSpStk: string;
  DocumentTypeCode: string;
  EntryDate: Date | number;
  TermsDescription: string;
  CommissionRemarks: string;
  ItemCode: string | number;
  JobLotDescription: string;
  ModifyDate: Date | string;
  OrderCategoryName: string;
  OrderItemRateUOMId: number;
  CompanyNameSpCAgent: string;
  OrderDueDate: Date | string;
  UomScheduleIdCmRate: number;
  BrokerAgentSupCustId: number;
  OrderExpiryDate: string | Date;
  SupplierRefNo: string | number;
  DocumentTypeDescription: string;
  DeliveryStartDate: Date | string;
  OrderCategoryDescription: string;
  SupplierCustomerIdStockParty: number;
};

export type TPurchaseOrderSearchCriteria = {
  ItemId?: number;
  ToDocNo?: number;
  FromDocNo?: number;
  ToDate?: Date | string;
  FromDate?: Date | string;
  Status?: number | string;
  SupplierCustomerId?: number;
  IsApproved?: number | string;
};

export type TPurchaseOrderEntry = {
  Id?: number;
  DocNo?: number;
  CityId?: number;
  CommRate?: number;
  PostUser?: number;
  CompanyId?: number;
  EntryUser?: number;
  IsAproved?: boolean;
  PostState?: boolean;
  CommAmount?: number;
  BranchesId?: number;
  ModifyUser?: number;
  ProjectsId?: number;
  BrokeryUom?: number;
  BrokeryRate?: number;
  OrderStatus?: string;
  DeliveryTerm: string;
  CatagorySrNo?: number;
  DeliveryDays?: number;
  OrderDueDays?: number;
  CashFreight?: boolean;
  AttachmentsList?: any;
  OrderSupCustId: number;
  BrokerAgentId?: number;
  BrokeryAmount?: number;
  OrderTaxable?: boolean;
  DocDate: Date | string;
  PaymentTermsId: number;
  DocumentTypeId?: number;
  OrganizationId?: number;
  CreditFreight?: boolean;
  FinancialYearId?: number;
  OrderCatagoryId?: number;
  RefrenenceParty?: number;
  EntryDate?: Date | string;
  OrderType?: string | null;
  ModifyDate?: Date | string;
  OrderDueDate: Date | string;
  BrokeryType?: string | null;
  UomScheduleIdCmRate?: number;
  BrokerAgentSupCustId?: number;
  RemarksHeader?: string | null;
  SupplierRefNo?: number | null;
  CommissionType?: string | null;
  OrderExpiryDate?: Date | string;
  PostDate?: Date | string | null;
  DeliveryRemarks?: string | null;
  PurchaseorderEmptyBagsList?: any;
  DeliveryStartDate?: Date | string;
  CommissionRemarks?: string | null;
  PurchaseOrderLabDeductionList?: any;
  SupplierCustomerIdStockParty?: number;
  PurchaseOrderExpensesChargeToProductsList?: any;
  purchaseOrderDetailList: TPurchaseOrderDetailEntry[];
};

export type TPurchaseOrderDetailEntry = {
  Id?: number;
  LineId?: number;
  UOMCode?: string;
  RateUom?: string;
  BagPrice?: number;
  ItemName?: string;
  BagWeight?: number;
  NetWeight?: number;
  TaxAmount?: number;
  TaxNameId?: number;
  RetailRate?: number;
  TaxPercent?: number;
  TotalAmount?: number;
  Crop?: string | null;
  OrderItemQty?: number;
  ActionTypeId?: number;
  Amount?: number | null;
  OrderItemRate?: number;
  OrderItemUOMId?: number;
  TaxName?: string | null;
  UOMDescription?: number;
  EquivalentRate?: number;
  JobLotId?: null | number;
  PurchaseOrderId?: number;
  CityArea?: string | null;
  Moisture?: string | null;
  JobLotDescription?: string;
  OrderItemId?: null | number;
  OrderItemRateUOMId?: number;
  LabSampleNo?: number | null;
  OrderRemarks?: string | null;
  TaxableStatus?: string | null;
  AmountCalcType?: string | null;
  InvLabSampleAnalysisHeaderId?: number;
};

export type TDetailItem = {
  Id: number;
  UOMCode: string;
  ItemName: string;
  ItemUomId: number;
  Equivalent: number;
};
