export type TPurchaseOrderHistory = {
  Id: number;
  Crop: string;
  DocNo: number;
  PoDId: number;
  Amount: number;
  BalQty: number;
  RejQty: number;
  BagPrice: number;
  CityArea: string;
  CommRate: number;
  ItemName: string;
  JobLotId: number;
  Moisture: string;
  PostDate: string;
  PostUser: string;
  BagWeight: number;
  BalWeight: number;
  CompanyId: number;
  EntryUser: number;
  NetWeight: number;
  OrderType: string;
  PPBagRate: string;
  PostState: string;
  TermsCode: string;
  BaseUnitId: number;
  BranchesId: number;
  CommAmount: number;
  Equivalent: number;
  IsApproved: string;
  ItemTypeId: number;
  JobLotCode: string;
  ModifyUser: string;
  ProjectsId: number;
  UOMCodeItm: string;
  ItemClassId: number;
  JuteBagRate: string;
  LabSampleNo: string;
  OrderItemId: number;
  OrderStatus: string;
  PPBagWeight: string;
  ReceivedQty: number;
  UOMCodeRate: string;
  CatagorySrNo: number;
  DeliveryDays: number;
  DeliveryTerm: string;
  ItemCategory: string;
  OrderDueDays: number;
  OrderItemQty: number;
  OrderRemarks: string;
  PurchaseGLAC: number;
  SupplierName: string;
  UserNameAusr: string;
  UserNameEusr: string;
  UserNameMusr: string;
  JuteBagWeight: string;
  OrderItemRate: number;
  OrderTaxable: boolean;
  RemarksHeader: string;
  TaxableStatus: string;
  AmountCalcType: string;
  CommissionType: string;
  DocDate: Date | string;
  DocumentTypeId: number;
  EquivalentRate: number;
  ItemCategoryId: number;
  OrderItemUOMId: number;
  OrderSupCustId: number;
  OrganizationId: number;
  PaymentTermsId: number;
  ReceivedWeight: number;
  CompanyNameSpRp: string;
  DeliveryRemarks: string;
  NoOfAttachments: number;
  OrderCatagoryId: number;
  PurchaseOrderId: number;
  RefrenenceParty: number;
  CompanyNameSpStk: string;
  DocumentTypeCode: string;
  EntryDate: Date | number;
  TermsDescription: string;
  CommissionRemarks: string;
  ItemCode: string | number;
  JobLotDescription: string;
  ModifyDate: Date | string;
  OrderCategoryName: string;
  OrderItemRateUOMId: number;
  CompanyNameSpCAgent: string;
  OrderDueDate: Date | string;
  UomScheduleIdCmRate: number;
  BrokerAgentSupCustId: number;
  OrderExpiryDate: string | Date;
  SupplierRefNo: string | number;
  DocumentTypeDescription: string;
  DeliveryStartDate: Date | string;
  OrderCategoryDescription: string;
  SupplierCustomerIdStockParty: number;
};
