export const route = {
  LOGIN: '/',
  SYLLABUS_MANAGEMENT: '/syllabus-management',
  CLASS_MANAGEMENT: '/class-management',
  SIGN_fORM: '/signform',
  STUDENT_PROFILE: '/profile',
  STUDENT_SYLLABUS: '/syllabus1',
  SYLLABUS_STATUS: '/syllabusfile',
  ASSESSMENT: '/assessment',
  SUBJECT1: '/subject',
  LOGIN_FORM: '/loginform',
  DASHBOARD: '/dashboard',
  DASHBOARD_SUB_TOPIC: '/dashboardsubtopic',
  CLASS_SYLLABUS_BY_TOPIC: '/classsyllabusdivisionbytopic',
  SYLLABUS_DIVISION_TOPIC: '/syllabusdivisionbytopic',
};
