export type TJournalVoucherData = {
  Id: number;
  DocumentTypeId: number;
  DocumentTypeSrNo: number;
  VoucherCode: number;
  VoucherDate: string;
  RemarksOtherLingo: string;
  FinancialYearId: number;
  Remarks: string;
  EntryDate: Date | string;
  EntryUser: number;
  ModifyDate: Date | string;
  ModifyUser: number;
  OrganizationId: number;
  BranchId: number;
  CompanyId: number;
  VoucherAmount: number;
  voucherDetailList: TVoucherDetailList[];
};
export type TVoucherDetailList = {
  AccountIdC: number;
  AccountIdD: number;
  AccountTitleC: string;
  AccountTitleD: string;
  AgainstAccountId: number;
  JobLotId: number;
  Comments: string;
  CheqNoDetail: string;
  DebitAmount: number;
  CreditAmount: number;
  LineId: number;
};
export type TAccountsCombo = {
  Id: number;
  AccountTitle: string;
};
export type TDetailItem = {
  Id: number;
  ItemName: string;
  ItemCode: number;
  InventoryParentCategoriesId: number;
  ItemCategoryId: number;
  ItemTypeId: number;
  PurchaseGLAC: number;
  SaleGLAC: number;
  COGSGLAC: number;
};
export type TDetailPackUom = {
  Id: number;
  ItemId: number;
  ScheduleUnitId: number;
  Equivalent: number;
  BaseRateUom: false;
  UOMCode: string;
  EntryDate: Date | string;
  EntryUser: number;
  ModifyDate: Date | null;
  ModifyUser: number | null;
  OrganizationId: number;
  CompanyId: number;
  ItemName: string;
  ScheduleUnitName: string;
};
export type TWarehouse = {
  Id: number;
  WareHouseName: string;
};
export type TJournalVoucherHistory = {
  Id: number;
  VoucherCode: number;
  DocumentTypeId: number;
  DocumentTypeCode: string;
  VoucherDate: Date | string;
  ManualBillNo: number | null;
  AccountTitle: string | null;
  Remarks: string;
  VoucherAmount: number;
  UserName: string;
  CheqNo: number | null;
};
export type TStockTransfer = {
  Id: string;
  DocNo: number;
  DocDate: Date;
  EntryUser: string;
  EntryDate: Date;
  ModifyUser: string;
  ModifyDate: Date;
  ApprovedUser: string;
  ApprovalStatus: any;
  ApprovedDate: Date;
  Remarks: string;
  DocumentTypeId: number;
  OrganizationId: number;
  CompanyId: number;
  BranchesId: number;
  FinancialYearId: number;
  WsRmWareHouseToWareHouseStocTransferDetailList: TWsRmWareHouseToWareHouseStocTransferDetailList[];
};
export type TWsRmWareHouseToWareHouseStocTransferDetailList = {
  Id: number;
  WsRmStockTransferId: number;
  ItemId: number;
  ItemName: string;
  WareHouseFromId: number;
  WarehouseFromName: string;
  ItemUomId: number;
  ItemUomCode: string;
  ItemQty: number;
  BalQty: number;
  BalWeight: number;
  NetWeight: number;
  ItemRate: number;
  ItemAmount: number;
  WareHouseToId: number;
  WarehouseToName: string;
  RemarksDetail: string;
  ActionTypeId: number;
  LineId: number;
};
export type TStockTransferHistory = {
  Id: string;
  DocNo: number;
  DocDate: Date;
  EntryUser: string;
  EntryDate: Date;
  ModifyUser: string;
  ModifyDate: Date;
  ApprovedUser: string;
  ApprovalStatus: string;
  ApprovedDate: Date;
  Remarks: string;
  DocumentTypeId: number;
  OrganizationId: number;
  CompanyId: number;
  BranchesId: number;
  FinancialYearId: number;
};
