import { NativeButtonProps } from 'antd/es/button/button';

export type TItemHistoryTable = {
  RecordNo: number;
  Id: number;
  ItemCode: string;
  ItemName: string;
  BaseUnitId: number;
  ItemCategoryId: number;
  ItemTypeId: number;
  ItemClassId: number;
  PurchaseGLAC: number;
  SaleGLAC: number;
  COGSGLAC: number;
  HSCode: string;
  PackQty: number;
  ItemStatus: boolean;
  ManufactureId: number;
  ManufacturePartNo: string;
  BuyerSupplierId: number;
  BuyerPartNo: string;
  ProductNo: null | number;
  MinStockLevel: number;
  OptimalStockLevel: number;
  MaxStockLevel: number;
  ReorderLevel: number;
  ItemOriginId: number;
  CostPrice: number;
  UOMScheduleIdCostRate: number;
  PurchasePrice: number;
  UOMScheduleIdPurRate: number;
  RetailPrice: number;
  UOMScheduleIdRetailRate: number;
  WholeSalePrice: number;
  UOMScheduleIdWhsRate: number;
  AmountCalcType: null | string | number;
  BarcodeImage: string | ImageBitmap;
  BarcodeNo: number;
  BaseCropYear: string | number;
  ApplyGST: boolean;
  ApplyVAT: boolean;
  ApplyExciese: boolean;
  OtherTax: boolean;
  Pic1: null | ImageBitmap;
  Pic2: string | ImageBitmap;
  PostDate: Date | number;
  PostUser: number;
  PostState: boolean;
  OrganizationId: number;
  CompanyId: number;
  BranchesId: number;
  ProjectsId: number;
  GlStockAccountTitle: string;
  GlSaleAccountTitle: string;
  GlCgsAccountTitle: string;
  CategoryDescription: string;
  TypeDescription: string;
  UOMCode: string;
  InvParentCateDescription: string;
  ClassGroupName: string;
  ProductType: null | string;
  MasterItemId: number;
  ItemSpecification: string | number;
  UomLookUpId: number;
  ItemAliasName: string;
  PurchaseTypeLookUpId: number;
  IsExpirable: boolean;
  ShelfLife: number;
  IsDiscountable: boolean;
  SaleTaxPurPercent: number;
  AtRetailPriceTax: boolean;
  AtPurcahsePriceTax: boolean;
  SaleTaxSalesPercent: number;
  IsTaxable: boolean;
  DepreciationExpenseAcId: number;
  accumulatedDepreciationAcId: number;
  CapitalWipAcId: number;
  EntryUserName: string;
  EntryUserId: number;
  EntryDate: Date;
  EntryUserProfileImage: null | string;
  MoidifyUserProfileImage: null | string;
  NoOfAttachments: number;
};

export type TPurchaseOrderHistory = {
  Id: number;
  Crop: string;
  DocNo: number;
  PoDId: number;
  Amount: number;
  BalQty: number;
  RejQty: number;
  BagPrice: number;
  CityArea: string;
  CommRate: number;
  ItemName: string;
  JobLotId: number;
  Moisture: string;
  PostDate: string;
  PostUser: string;
  BagWeight: number;
  BalWeight: number;
  CompanyId: number;
  EntryUser: number;
  NetWeight: number;
  OrderType: string;
  PPBagRate: string;
  PostState: string;
  TermsCode: string;
  BaseUnitId: number;
  BranchesId: number;
  CommAmount: number;
  Equivalent: number;
  IsApproved: string;
  ItemTypeId: number;
  JobLotCode: string;
  ModifyUser: string;
  ProjectsId: number;
  UOMCodeItm: string;
  ItemClassId: number;
  JuteBagRate: string;
  LabSampleNo: string;
  OrderItemId: number;
  OrderStatus: string;
  PPBagWeight: string;
  ReceivedQty: number;
  UOMCodeRate: string;
  CatagorySrNo: number;
  DeliveryDays: number;
  DeliveryTerm: string;
  ItemCategory: string;
  OrderDueDays: number;
  OrderItemQty: number;
  OrderRemarks: string;
  PurchaseGLAC: number;
  SupplierName: string;
  UserNameAusr: string;
  UserNameEusr: string;
  UserNameMusr: string;
  JuteBagWeight: string;
  OrderItemRate: number;
  OrderTaxable: boolean;
  RemarksHeader: string;
  TaxableStatus: string;
  AmountCalcType: string;
  CommissionType: string;
  DocDate: Date | string;
  DocumentTypeId: number;
  EquivalentRate: number;
  ItemCategoryId: number;
  OrderItemUOMId: number;
  OrderSupCustId: number;
  OrganizationId: number;
  PaymentTermsId: number;
  ReceivedWeight: number;
  CompanyNameSpRp: string;
  DeliveryRemarks: string;
  NoOfAttachments: number;
  OrderCatagoryId: number;
  PurchaseOrderId: number;
  RefrenenceParty: number;
  CompanyNameSpStk: string;
  DocumentTypeCode: string;
  EntryDate: Date | number;
  TermsDescription: string;
  CommissionRemarks: string;
  ItemCode: string | number;
  JobLotDescription: string;
  ModifyDate: Date | string;
  OrderCategoryName: string;
  OrderItemRateUOMId: number;
  CompanyNameSpCAgent: string;
  OrderDueDate: Date | string;
  UomScheduleIdCmRate: number;
  BrokerAgentSupCustId: number;
  OrderExpiryDate: string | Date;
  SupplierRefNo: string | number;
  DocumentTypeDescription: string;
  DeliveryStartDate: Date | string;
  OrderCategoryDescription: string;
  SupplierCustomerIdStockParty: number;
};

export type TPurchaseOrderSearchCriteria = {
  ItemId?: number;
  ToDocNo?: number;
  FromDocNo?: number;
  ToDate?: Date | string;
  FromDate?: Date | string;
  Status?: number | string;
  SupplierCustomerId?: number;
  IsApproved?: number | string;
};
