export type TAccountsCombo = {
  Id: number;
  AccountTitle: string;
};
export type TDetailItem = {
  Id: number;
  PriceTypeId: number;
  PriceTypeDescription: string;
  ItemPrice: number;
  AddRate: number | null;
  LessRate: number | null;
  ItemId: number;
  ItemName: string;
  ItemUomId: number;
  Equivalent: number;
  UOMCode: string;
  RateUomId: number;
  PreviousRateUom: string;
  BaseRateUom: number | null;
  RateUom: number;
};
export type TDetailPackUom = {
  Id: number;
  ItemId: number;
  Equivalent: number;
  BaseRateUom: false;
  UOMCode: string;
  ItemName: string;
  PriceTypeId: number;
  PriceTypeDescription: string;
  ItemPrice: number;
  AddRate: number | null;
  LessRate: number | null;
  EffectedDate: Date;
  BranchName: string;
  ItemUomId: number;
  RateUomId: number;
  PreviousRateUom: string;
  RateUom: number;
};
export type TStockAdjustment = {
  Id: number;
  DocumentTypeId: number;
  DocDate: Date;
  DocNo: number;
  RemarksHeader: string;
  AdjustmentTypeId: number;
  OrganizationId: number;
  CompanyId: number;
  BranchesId: number;
  FinancialYearId: number;
  EnteryUserId: number;
  EnteryDate: Date;
  ModifyUserId: number;
  ModifyDate: Date;
  ApprovalUserId: number;
  ApprovedDate: Date;
  PrintPreview: boolean;
  InvStockAdjustmentDetailslist: InvStockAdjustmentDetail[];
};
export type InvStockAdjustmentDetail = {
  Id: number;
  PackUom: string;
  Qty: number;
  ItemName: string;
  WarehouseId: number;
  WareHouseName: string;
  ItemId: number;
  PackUomId: number;
  NetWeight: number;
  ItemRate: number;
  RateUomId: number;
  Amount: number;
  DebitAccountId: number;
  RemarksDetail: string;
  ActionTypeId: number;
  RateUom: string;
  AccountTitle: string;
  CreditAccountId: number;
};
export type TWareHouse = {
  Id: number;
  WareHouseName: string;
};

export type TAccountTitle = {
  Id: number;
  AccountTitle: string;
};
export type TStockAdjustmentHistory = {
  Id: number;
  DocNo: number;
  DocDate: Date | string;
  VoucherHeadId: number;
  EntryType: string;
  EntryUser: number;
  EnteryDate: Date;
  ModifyUser: string;
  ModifyDate: Date;
  Remarks: string;
};
