export type TDefineItemData = {
  ApplyExciese: boolean;
  ApplyGST: boolean;
  ApplyVAT: boolean;
  ItemStatus: boolean;
  OtherTax: boolean;
  PostState: boolean;
  EntryDate: string | Date;
  ModifyDate: string | Date;
  PostDate: string | Date;
  CostPrice: number;
  MaxStockLevel: number;
  OptimalStockLevel: number;
  MinStockLevel: number;
  PackQty: number;
  PurchasePrice: number;
  ReorderLevel: number;
  RetailPrice: number;
  WholeSalePrice: number;
  BaseUnitId: number;
  BranchesId: number;
  BuyerSupplierId: number;
  COGSGLAC: number;
  CompanyId: number;
  EntryUser: number;
  Id: number;
  ItemCategoryId: number;
  ItemClassId: number;
  ItemTypeId: number;
  ManufactureId: number;
  ModifyUser: number;
  OrganizationId: number;
  PostUser: number;
  ProjectsId: number;
  PurchaseGLAC: number;
  SaleGLAC: number;
  DepreciationExpenseAcId: number;
  accumulatedDepreciationAcId: number;
  CapitalWipAcId: number;
  UOMScheduleIdCostRate: number;
  UOMScheduleIdPurRate: number;
  UOMScheduleIdRetailRate: number;
  UOMScheduleIdWhsRate: number;
  AmountCalcType: string | null;
  BaseCropYear: string | null;
  BuyerPartNo: string | null;
  HSCode: string | null;
  ItemCode: string;
  ItemName: string;
  ManufacturePartNo: string | null;
  Pic1: string | null;
  Pic2: string | null;
  ProductNo: string | null;
  BarcodeImage: string | null;
  BarcodeNo: string;
  ProductType: string | null;
  ItemOriginId: number;
  BaseRateUnitId: number;
  ItemAliasName: string;
  ItemSpecification: string | null;
  UomLookUpId: number;
  MasterItemId: number;
  PurchaseTypeLookUpId: number;
  IsExpirable: boolean;
  IsDiscountable: boolean;
  IsTaxable: boolean;
  ShelfLife: number;
  SaleTaxPurPercent: number;
  AtRetailPriceTax: boolean;
  AtPurcahsePriceTax: boolean;
  SaleTaxSalesPercent: number;
  TaxTypeId: number;
  ItemGroupId: number;
  Equivalent: number;
  RateEquivalent: number;
  AttachmentsList: any | null; // Update with appropriate type
  ItemAllocationlist: any | null;
};
export type TDefineItemDataOnAdd = {
  ItemStatus: boolean;
  EntryDate: string | Date;
  ModifyDate: string | Date;
  PostDate: string | Date;
  PackQty: number;
  PurchasePrice: number;
  WholeSalePrice: number;
  BaseUnitId: number;
  BranchesId: number;
  COGSGLAC: number;
  CompanyId: number;
  EntryUser: number;
  Id: number;
  ItemCategoryId: number;
  ItemClassId: number;
  ItemTypeId: number;
  OrganizationId: number;
  PurchaseGLAC: number;
  SaleGLAC: number;
  UOMScheduleIdCostRate: number;
  UOMScheduleIdPurRate: number;
  UOMScheduleIdRetailRate: number;
  UOMScheduleIdWhsRate: number;
  HSCode: string | null;
  ItemCode: string;
  ItemName: string;
  Pic1: string | null;
  Pic2: string | null;
  ProductNo: string | null;
  BarcodeImage: string | null;
  BarcodeNo: string;
  ItemAliasName: string;
  ItemSpecification: string | null;
  ItemAllocationlist: any | null;
};

export type TDefineItemDataonUpdate = {
  rowVersion: number;
  ItemStatus: boolean;
  EntryDate: string | Date;
  ModifyDate: string | Date;
  PostDate: string | Date;
  PackQty: number;
  PurchasePrice: number;
  WholeSalePrice: number;
  BaseUnitId: number;
  BranchesId: number;
  COGSGLAC: number;
  CompanyId: number;
  EntryUser: number;
  Id: number;
  ItemCategoryId: number;
  ItemClassId: number;
  ItemTypeId: number;
  OrganizationId: number;
  PurchaseGLAC: number;
  SaleGLAC: number;
  UOMScheduleIdCostRate: number;
  UOMScheduleIdPurRate: number;
  UOMScheduleIdRetailRate: number;
  UOMScheduleIdWhsRate: number;
  HSCode: string | null;
  ItemCode: string;
  ItemName: string;
  Pic1: string | null;
  Pic2: string | null;
  ProductNo: string | null;
  BarcodeImage: string | null;
  BarcodeNo: string;
  ItemAliasName: string;
  ItemSpecification: string | null;
  ItemAllocationlist: any | null;
};
