export type TGRNDetailTableAdd = {
  PrintPreview: boolean;
  OrganizationId: number;
  CompanyId: number;
  BranchesId: number;
  FinancialYearId: number;
  EntryDate: string;
  ModifyDate: string;
  EntryUser: number;
  ModifyUser: number;
  DocumentTypeId: number;
  DocDate: string;
  DocNo: number;
  SupplierCustomerId: number;
  PartyWeight: number;
  FactoryWeight: number;
  VehicleType: string;
  VehicleNo: string;
  GpNo: number;
  DeliveryTerm: string;
  BiltyNo: string;
  TransporterId: number;
  CarriageAmount: number;
  RemarksHeader: string;
  invGrnDetail: InvGrnDetail[];
};
export type InvGrnDetail = {
  Id: number;
  PurchaseOrderId: number;
  PurchaseOrderDetailId: number;
  PurchaserOrderNo: number;
  ItemId: number;
  ItemUomId: number;
  ItemQty: number;
  WarehouseId: number;
  JobLotId: number;
  AreaCity: string;
  GrossWeight: number;
  AdLsWeight: number;
  NetBillWeight: number;
  StockWeight: number;
  CommentsDetail: string;
  ActionTypeId: number;
};
