export type TAccountsCombo = {
  Id: number;
  AccountTitle: string;
};
export type TOtherItem = {
  Id: number;
  OtherItemName: string;
  OtherItemType: string;
  StockGLAcId: number;
  AccountTitleStock: string;
  SaleGLAcId: number;
  AccountTitleSales: string;
  CogsGLAcId: number;
  AccountTitleCgs: string;
  CompanyId: number;
  StockGLAc: string;
  SaleGLAc: string;
  CogsGLAc: string;
};
export type TDetailPackUom = {
  Id: number;
  ItemId: number;
  Equivalent: number;
  BaseRateUom: false;
  UOMCode: string;
  ItemName: string;
  PriceTypeId: number;
  PriceTypeDescription: string;
  ItemPrice: number;
  AddRate: number | null;
  LessRate: number | null;
  EffectedDate: Date;
  BranchName: string;
  ItemUomId: number;
  RateUomId: number;
  PreviousRateUom: string;
  RateUom: number;
};

export type TDetailItem = {
  Id: number;
  PriceTypeId: number;
  PriceTypeDescription: string;
  ItemPrice: number;
  AddRate: number | null;
  LessRate: number | null;
  ItemId: number;
  ItemName: string;
  ItemUomId: number;
  Equivalent: number;
  UOMCode: string;
  RateUomId: number;
  PreviousRateUom: string;
  BaseRateUom: number | null;
  RateUom: number;
};

export type TStockTransferNotesHistory = {
  Id: number;
  DocNo: number;
  DocDate: Date | string;
  LocationFrom: string;
  LocationTo: string;
  RequestStatus: string;
  EntryUser: string;
  RemarksHeader: string;
  IssuedQty: number;
  IssuedAmount: number;
  ReceivedNo: number;
  ReceivedDate: Date;
  IsReffered: string;
  EntryDate: Date | string;
  EntryUserId: number;
  ModifyDate: Date | string;
  ModifyUserId: number;
  ModifyUserName: string;
  CompLogoImage: string;
  EntryUserProfileImageUrl: string;
  ModifyUserProfileImageUrl: string;
};
export type TLoadORderHistory = {
  Id: string;
  RequisitionDetailId: string;
  OrderDate: Date;
  OrderNo: number;
  SourceId: number;
  SourceLocation: string;
  DestinationId: number;
  DestinationLocation: string;
  ItemId: number;
  ItemName: string;
  ItemUomId: number;
  PackUom: string;
  PackEquivalent: string | any;
  ReqQty: number;
  ApprovedQty: number;
  ReqRate: number;
  ReqWeight: number;
  StockWeight: number;
  ReqAmount: number;
  RemarksHeader: string;
  WareHouseName: string;
  AvailableStock: number;
  AvailableWeight: number;
  BillWeight: number;
  IssuedAmount: number;
  IssuedQty: number;
  IssuedRate: number;
  ExpenseAmount: number;
  ItemNetAmount: number;
  ActionTypeId: number;
  WarehouseId: number;
  LineId: number;
  WsRmRequisitionPoDetailId: number;
  WsRmRequisitionPoId: number;
  WsRmStockTransferNotesId: number;
  RemarksDetail: string;
  UOMCode: string;
  RequisitionNo: number;
};
export type TStockTransferNotes = {
  PrintPreview: boolean;
  IsApproved: boolean;
  ApprovedDate: Date;
  DocDate: Date;
  EntryDate: Date;
  ModifyDate: Date;
  ApprovedUserId: number;
  BranchesId: number;
  FinancialYearId: number;
  CompanyId: number;
  DocumentTypeId: number;
  DestinationLocationId: number;
  DocNo: number;
  EntryUserId: number;
  Id: number;
  ModifyUserId: number;
  OrganizationId: number;
  SourceLocationId: number;
  WsRmRequisitionPoId: number;
  RemarksHeader: string;
  ReqStatus: string;
  WsRmStockTransferNotesDetailsList: TWsRmStockTransferNotesDetailsList[];
  WsRmStockTransferNotesExpensesList: TWsRmStockTransferNotesExpensesList[];
  AttachmentsList: null;
  VoucherHeadInvoices: null;
  InventoryStockEvalautionDetailslist: null;
};
export type TWsRmStockTransferNotesDetailsList = {
  BillWeight: number;
  IssuedAmount: number;
  IssuedQty: number;
  IssuedRate: number;
  StockWeight: number;
  ExpenseAmount: number;
  ItemNetAmount: number;
  Id: number;
  ActionTypeId: number;
  ItemId: number;
  ItemUomId: number;
  WarehouseId: number;
  LineId: number;
  WsRmRequisitionPoDetailId: number;
  WsRmRequisitionPoId: number;
  WsRmStockTransferNotesId: number;
  RemarksDetail: string;
  WareHouseName: string;
  ItemName: string;
  UOMCode: string;
  PackEquivalent: number;
  RequisitionNo: number;
  ApprovedQty: number;
};
export type TWsRmStockTransferNotesExpensesList = {
  ItemId: number;
  ItemName: string;
  Qty: number;
  Rate: number;
  Amount: number;
  Remarks: string;
};
