export type TOtherItem = {
  Id: number;
  OtherItemName: string;
  OtherItemType: string;
  StockGLAcId: number;
  AccountTitleStock: string;
  SaleGLAcId: number;
  AccountTitleSales: string;
  CogsGLAcId: number;
  AccountTitleCgs: string;
  CompanyId: number;
  StockGLAc: string;
  SaleGLAc: string;
  CogsGLAc: string;
};
export type TDetailPackUom = {
  Id: number;
  ItemId: number;
  Equivalent: number;
  BaseRateUom: false;
  UOMCode: string;
  ItemName: string;
  PriceTypeId: number;
  PriceTypeDescription: string;
  ItemPrice: number;
  AddRate: number | null;
  LessRate: number | null;
  EffectedDate: Date;
  BranchName: string;
  ItemUomId: number;
  RateUomId: number;
  PreviousRateUom: string;
  RateUom: number;
};

export type TDetailItem = {
  Id: number;
  PriceTypeId: number;
  PriceTypeDescription: string;
  ItemPrice: number;
  AddRate: number | null;
  LessRate: number | null;
  ItemId: number;
  ItemName: string;
  ItemUomId: number;
  Equivalent: number;
  UOMCode: string;
  RateUomId: number;
  PreviousRateUom: string;
  BaseRateUom: number | null;
  RateUom: number;
};

export type TStockReceivedNoteHistory = {
  Id: number;
  DocumentTypeId: string;
  DocNo: number;
  DocDate: Date | string;
  ReceivedQty: number;
  ReceivedAmount: number;
  StockTransferNo: string;
  DispatchedFrom: string;
  DispactchedTo: string;
  RequestStatus: string;
  TotalReceivedQty: number;
  TotalReceivedAmount: number;
  EntryUser: string;
  EntryDate: Date | string;
  RemarksHeader: string;
  NoOfAttachments: number;
};
export type TDispatchedSTNLoadHistory = {
  Id: number;
  TransferNotesDetailId: number;
  DocDate: Date | string;
  DocNo: number;
  SourceLocationId: number;
  SourceLocation: string;
  DestinationLocationId: number;
  DestinationLocation: string;
  RemarksHeader: string;
  ItemId: number;
  ItemName: string;
  ItemUomId: number;
  UOMCode: string;
  PackEquivalent: number;
  IssuedQty: number;
  IssuedRate: number;
  IssuedAmount: number;
  RemarksDetail: string;
  BillWeight: number;
  StockWeight: number;
  WsRmRequisitionPoId: number;
  WsRmRequisitionPoDetailId: number;
  RequisitionNo: number;
  ReqStatus: string;
};
export type TLoadORderHistory = {
  Id: number;
  WsRmStockTransferNotesId: number;
  WsRmStockTransferNotesDetailId: number;
  WarehouseId: number;
  ItemId: number;
  ItemUomId: number;
  ReceivedQty: number;
  IssuedQuantity: number;
  BillWeight: number;
  StockWeight: number;
  ReceivedRate: number;
  ReceivedAmount: number;
  ExpenseAmount: number;
  AvailableStock: number;
  AvailableWeight: number;
  ItemNetAmount: number;
  RemarksDetail: string;
  ActionTypeId: number;
  LineId: number;
  WsRmStockReceivedNotesId: number;
  WareHouseName: string;
  ItemName: string;
  UOMCode: string;
  PackEquivalent: number;
  TransferNo: number;
  AvgRate: number;
  // STN
  TransferNotesDetailId: number;
  DocDate: Date | string;
  DocNo: number;
  SourceLocationId: number;
  SourceLocation: string;
  DestinationLocationId: number;
  DestinationLocation: string;
  RemarksHeader: string;
  IssuedQty: number;
  IssuedRate: number;
  IssuedAmount: number;
  WsRmRequisitionPoId: number;
  WsRmRequisitionPoDetailId: number;
  RequisitionNo: number;
  ReqStatus: string;
};

export type TStockReceivedNotes = {
  IsApproved: boolean;
  WsRmStockTransferNotesId: number;
  Id: number;
  OrganizationId: number;
  CompanyId: number;
  BranchesId: number;
  FinancialYearId: number;
  DocumentTypeId: number;
  EntryDate: Date | string;
  EntryUserId: number;
  ModifyDate: Date | string;
  ModifyUserId: number;
  ApprovedDate: Date | string;
  ApprovedUserId: number;
  DocNo: number;
  DocDate: Date | string;
  SourceLocationId: number;
  DestinationLocationId: number;
  ReqStatus: number;
  RemarksHeader: string;
  PrintPreview: boolean;
  WsRmStockReceivedNotesDetailList: TWsRmStockReceivedNotesDetailList[];
  WsRmStockReceivedNotesExpensesList: TWsRmStockReceivedNotesExpensesList[];
  VoucherHeadInvoices: null;
  AttachmentsList: any[];
};
export type TWsRmStockReceivedNotesDetailList = {
  Id: number;
  WsRmStockTransferNotesId: number;
  WsRmStockTransferNotesDetailId: number;
  WarehouseId: number;
  ItemId: number;
  ItemUomId: number;
  ReceivedQty: number;
  IssuedQuantity: number;
  BillWeight: number;
  StockWeight: number;
  ReceivedRate: number;
  ReceivedAmount: number;
  ExpenseAmount: number;
  ItemNetAmount: number;
  RemarksDetail: string;
  ActionTypeId: number; // 1 for  insert, 2 For Update , 3 For Delete
  LineId: number;
  WsRmStockReceivedNotesId: number;
  WareHouseName: string;
  ItemName: string;
  UOMCode: string;
  PackEquivalent: number;
  TransferNo: number;
};
export type TWsRmStockReceivedNotesExpensesList = {
  ItemId: number;
  Qty: number;
  Rate: number;
  Amount: number;
  Id: number;
  WsRmStockReceivedNotesId: number;
  Remarks: string;
  OtherItemName: string;
};
